
# Sensor driver configuration
image_inference_node:
  ros__parameters:
    verbose: True        # If true - print debug info about sent requests and received responses, recognized classes.
    ticker_interval_sec: 0.1
    server_host: 'jetson.local'  # Jetson Nano "host" IP address (not container)
    server_port: 5001
    startup_delay_sec: 5.0
    image_topic: '/camera/image_raw/compressed'
    frame_id_out: 'camera'
    min_confidence: 0.6    # do not publish if below this confidence threshold
    objects_allowed: ['']  # Empty list means allow all detected objects.
    #objects_allowed: ['person', 'cup', 'bottle', 'cell phone', 'banana', 'book', 'scissors', 'dog', 'cat']  # Not case sensitive.
    stats_period_sec: 5.0
    use_server_cam: True  # Default: false. If True - do not send images from ROS, the server's camera feeds inference engine directly
    request_jpeg_every_n: 5  # in server camera mode, request JPEG every N requests. 0 = always request JPEG, -1 = never, default=5.



# Perception adapter (BT topics relay) configuration
perception_adapter:
  ros__parameters:
    verbose: True        # If true - print debug info about recognized and passed detections.
    ticker_interval_sec: 0.1
    detection_topic: '/image_inference_detections'
    #face_detected_sound: 'my_face.wav'
    face_detected_text: 'I see you!'
    min_confidence: 0.6
    face_cooldown_sec: 2.0
    gesture_cooldown_sec: 1.0
    camera_center_x: 320.0  # Assuming 640x480 input images. Adjust if different.
    target_label: 'person'  # The "face detected" logic is applied only to this object class.
    # Optional mapping of incoming class labels to "normalized class labels". Normally is not needed:
    label_map_json: '{}'  # example: {"0":"person","1":"cat","cup_small":"cup"}',
    # Optional JSON string mapping object labels to "gestures". If not set, capitalized label will be used:
    gesture_map_json: '{"bottle":"STOP", "cup":"OK", "banana":"LIKE", "cat":"MEOW", "dog":"WOOF"}'
    # Optional JSON string mapping gestures/commands to speech output. If not set, the gesture name will be used:
    speech_map_json: '{"STOP":"Stop immediately!","OK":"good stuff!","scissors":"Careful, sharp!","FIRE_HYDRANT":"Fire hydrant - do not park!"}'

# Stereo -> PointCloud2 node parameters:
disparity_client_node:
  ros__parameters:
    verbose: True        # If true - print debug info.
    ticker_interval_sec: 0.1   # 10 Hz UDP socket poll timer
    bind_ip: '0.0.0.0'
    port: 5005
    cloud_topic: '/stereo/sparse_cloud'
    frame_id: 'stereo_camera'
    socket_timeout_sec:  0.0   # 0 for non-blocking
    log_every_n_packets: 10    # 0 for no log
    color_patch_fraction: 0.5  # center patch size relative to cell
    use_mean_color: True
    image_topic: 'camera/image_raw'
    tcp_host: 'jetson.local'
    tcp_port: 5006
    request_image_every_sec: 0.5
    jpeg_max_width: 320
    jpeg_max_height: 180
    jpeg_quality: 60
    tcp_timeout_sec: 5.0
