
# Sensor driver configuration
image_inference_node:
  ros__parameters:
    ticker_interval_sec: 0.1
    #server_host: '127.0.0.1'
    server_host: '172.17.1.164'  # Jetson Nano "host" IP address (not container)
    server_port: 5001
    startup_delay_sec: 5.0
    image_topic: '/camera/image_raw/compressed'
    frame_id_out: "camera"
    min_confidence: 0.6    # do not publish if below this confidence threshold
    objects_allowed: ['person', 'cup', 'dog', 'cat']  # Case sensitive. Empty list means allow all detected objects
    stats_period_sec: 5.0
    use_server_cam: False  # do not send images from ROS, the server's camera feeds inference engine directly


# Perception adapter (BT topics relay) configuration
perception_adapter:
  ros__parameters:
    ticker_interval_sec: 0.1
    detection_topic: '/image_inference_detections'
    #face_detected_sound: 'my_face.wav'
    face_detected_text: 'I see you!'
    min_confidence: 0.6
    face_cooldown_sec: 2.0
    camera_center_x: 320.0
    target_label: 'person'
